# Chatter
Semi-automatic bout segmentation from bird song recordings using acoustic features such as Spectral Flux, Energy, and MFCC coefficients.

In [1]:
# Importing functionalities
from audio_utils import *
from chatter_core import *
from visualizations import *
import warnings
# Suppress all warnings
warnings.filterwarnings("ignore")

In [2]:
# Making initial dataframe of song recordings
root_dir = "Songs"
df = create_initial_dataset(root_dir)
df.head()

             species bird_id                        wav_location  song_id
0  Geospiza-scandens   46234   Songs/Geospiza-scandens-46234.wav        0
1    Geospiza-fortis   82869     Songs/Geospiza-fortis-82869.wav        0
2  Melospiza-melodia  599851  Songs/Melospiza-melodia-599851.wav        0
3  Melospiza-melodia  663741  Songs/Melospiza-melodia-663741.wav        1
4        Zebra-finch   10000         Songs/Zebra-finch-10000.wav        0

In [3]:
# Preparing model, processor, and precomputing bout detection
birdnet_model_path  = "BirdNETmodel"
extractor = AudioFeatureExtractor(
    use_birdnet=True,
    birdnet_model_path=birdnet_model_path
)
df = df.join(df.apply(extractor.compute_all_features, axis=1))

In [4]:
# Launching Chatter
chatter = Chatter(df, extractor)
chatter.display()

VBox(children=(HBox(children=(Dropdown(description='Select Bird:', options=(('Geospiza-scandens 46234', 0), ('…

Output()

In [9]:
# This dataframe contains your detected bouts aswell as their respective metadata
chatter.bouts_df

,species,bird_id,wav_location,song_id,bout_id,duration,onset,offset,wavstart,wavend,intersong_interval,bout_wav
0,Melospiza-melodia,663741,Songs/Melospiza-melodia-663741.wav,1,0,2.090,0.000,2.090,0.000,2.840000,NaN,bouts_audio/Melospiza-melodia_663741_bout0.wav
1,Melospiza-melodia,663741,Songs/Melospiza-melodia-663741.wav,1,1,2.160,11.099,13.259,10.349,14.009000,9.009,bouts_audio/Melospiza-melodia_663741_bout1.wav
2,Melospiza-melodia,663741,Songs/Melospiza-melodia-663741.wav,1,2,1.000,16.000,17.000,15.500,17.500000,2.741,bouts_audio/Melospiza-melodia_663741_bout2.wav
3,Melospiza-melodia,663741,Songs/Melospiza-melodia-663741.wav,1,3,3.687,18.000,21.687,17.500,22.187000,1.000,bouts_audio/Melospiza-melodia_663741_bout3.wav
4,Melospiza-melodia,663741,Songs/Melospiza-melodia-663741.wav,1,4,1.115,28.862,29.977,28.112,30.000272,7.175,bouts_audio/Melospiza-melodia_663741_bout4.wav